pipeline {
    agent { label 'jenkins-worker' }

    environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    DOCKER_IMAGE = "yknk/test-node-app"
}

    stages {
        stage('Pull Code') {
            steps {
                echo 'Pulling code from GitHub...'
                checkout scm
            }
        }

       stage('Build Docker Image') {
    steps {
        echo '🐳 Building Docker image...'
        sh 'docker build -t $DOCKER_IMAGE -f "Homework_Yakovenko/Step Project 2/Dockerfile" "Homework_Yakovenko/Step Project 2"'
    }
}

        stage('Run Tests') {
            steps {
                echo 'Running tests inside container...'
                script {
                    try {
                        sh 'docker run --rm $DOCKER_IMAGE test'
                    } catch (err) {
                        error("❌ Tests failed")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                sh '''
                    echo "$DOCKERHUB_CREDENTIALS_PSW" | docker login -u "$DOCKERHUB_CREDENTIALS_USR" --password-stdin
                    docker push $DOCKER_IMAGE
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully!"
        }
        failure {
            echo "❌ Tests failed or push error occurred."
        }
    }
}
